import uuid

items = [
  {
  '_id': uuid.uuid4(),
  'type' : 'event',
  'communities': ['HKU'],
  'heading': '2022 Shun Hing Hightable',
  'sub_heading': 'Second Semester Hightable',
  'reason': 'Bi-annual Hightable Dinner',
  'price': 0,
  'negotiability': True,
  'description': 'A high table dinner is a HKU tradition where students congregate in formal dress and green gowns. Prominent alumni and guests are often invited to share their experience with students after dinner during High Table Talks. Faculties, residential halls and colleges, clubs and associations organise their own high table dinners from time to time.',
  'thumbnail_images': ['/item/hightable1.jpg', '/item/hightable2.jpg', '/item/hightable3.jpg', '/item/hightable4.jpg', '/item/hightable5.jpg'],
  'other_images': ['/item/hightable6.jpg'],
  'detail': [['Event Date', '25th, December, 1982'], ['Location', 'Jockey Club Village III Conference Hall'], ['Event Capacity', '50'], ['Condition', 'You must be a resident of Shun Hing College']],
  },
  {
    '_id': uuid.uuid4(),
    'type': 'ridebutnotcar',
    'communities': ['HKUST'],
    'heading': 'Nimbus 2000',
    'sub_heading': 'Nimbus Full Option 1991',
    'reason': 'I am selling because I\'ve graduated Hogwars!',
    'price': 4000,
    'negotiability': True,
    'description': "\"One of the Nimbus Racing Broom Company\'s most successful models. Highly reliable with good speed and exceptional handling — not for beginners!\" The Nimbus 2000 was a broomstick produced by the Nimbus Racing Broom Company as part of their successful line of racing brooms. At the time of its release in 1991, it was the fastest broomstick in production. The Nimbus 2000 easily outperformed its competitors on the Quidditch pitch until it was replaced as the top broomstick by the Nimbus 2001.",
    'thumbnail_images': ['/item/nimbus1.jpg', '/item/nimbus2.jpg', '/item/nimbus3.jpg', '/item/nimbus4.jpg', '/item/nimbus5.jpg'],
    'other_images': ['/item/nimbus6.jpg', '/item/nimbus7.jpg'],
    'detail': [['Bought On', '25th, July, 1991'], ['Brand', 'The Nimbus Broom Racing Company'], ['Condition', 'Burnt by Hungarian Horntail\'s flame'], ['Frequency of Use', 'Used every week during quidditch training']],
  },
  {
    '_id': uuid.uuid4(),
    'type': 'book',
    'communities': ['HKU', 'HKUST'],
    'heading': 'Hogwarts: A History',
    'sub_heading': 'Book concerning Hogwarts and its history, written by Bathilda Bagshot',
    'reason': 'I am selling because I\'ve graduated!', 
    'price': 100,
    'negotiability': False,
    'description': "\"Aren't you two ever going to read Hogwarts: A History?\" \"What's the point? You know it all by heart, we can just ask you.\"",
    'thumbnail_images': ['/item/book1.jpg', '/item/book2.jpg', '/item/book3.jpg', '/item/book4.jpg', '/item/book5.jpg'],
    'other_images': ['/item/book6.jpg', '/item/book7.jpg'],
    'detail': [['Bought On', '25th, December, 1997'], ['Writer', 'Bathilda Bagshot'], ['Condition', 'I had it while looking for horcrux, so...'], ['Frequency of Use', 'Everytime i had to look up something about Hogwarts']],
  },
  {
    '_id': uuid.uuid4(),
    'type': 'ridebutnotcar',
    'communities': ['HKUST'],
    'heading': 'Nimbus 2000',
    'sub_heading': 'Nimbus Full Option 1991',
    'reason': 'I am selling because I\'ve graduated!', 
    'price': 4000,
    'negotiability': True,
    'description': "\"One of the Nimbus Racing Broom Company\'s most successful models. Highly reliable with good speed and exceptional handling — not for beginners!\" The Nimbus 2000 was a broomstick produced by the Nimbus Racing Broom Company as part of their successful line of racing brooms. At the time of its release in 1991, it was the fastest broomstick in production. The Nimbus 2000 easily outperformed its competitors on the Quidditch pitch until it was replaced as the top broomstick by the Nimbus 2001.",
    'thumbnail_images': ['/item/nimbus1.jpg', '/item/nimbus2.jpg', '/item/nimbus3.jpg', '/item/nimbus4.jpg', '/item/nimbus5.jpg'],
    'other_images': ['/item/nimbus6.jpg', '/item/nimbus7.jpg'],
    'detail': [['Bought On', '25th, July, 1991'], ['Brand', 'The Nimbus Broom Racing Company'], ['Condition', 'Burnt by Hungarian Horntail\'s flame'], ['Frequency of Use', 'Used every week during quidditch training']],
  },
  {
    '_id': uuid.uuid4(),
    'type': 'ridebutnotcar',
    'communities': ['HKUST'],
    'heading': 'Nimbus 2000',
    'sub_heading': 'Nimbus Full Option 1991',
    'reason': 'I am selling because I\'ve graduated!', 
    'price': 4000,
    'negotiability': True,
    'description': "\"One of the Nimbus Racing Broom Company\'s most successful models. Highly reliable with good speed and exceptional handling — not for beginners!\" The Nimbus 2000 was a broomstick produced by the Nimbus Racing Broom Company as part of their successful line of racing brooms. At the time of its release in 1991, it was the fastest broomstick in production. The Nimbus 2000 easily outperformed its competitors on the Quidditch pitch until it was replaced as the top broomstick by the Nimbus 2001.",
    'thumbnail_images': ['/item/nimbus1.jpg', '/item/nimbus2.jpg', '/item/nimbus3.jpg', '/item/nimbus4.jpg', '/item/nimbus5.jpg'],
    'other_images': ['/item/nimbus6.jpg', '/item/nimbus7.jpg'],
    'detail': [['Bought On', '25th, July, 1991'], ['Brand', 'The Nimbus Broom Racing Company'], ['Condition', 'Burnt by Hungarian Horntail\'s flame'], ['Frequency of Use', 'Used every week during quidditch training']],
  }
]