# Generated by Django 4.0.5 on 2022-07-02 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=15)),
                ('heading', models.CharField(max_length=30)),
                ('sub_heading', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('negotiability', models.BooleanField(default=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('communities', models.ManyToManyField(to='base.community')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('events_hosted', models.IntegerField(blank=True, default=0, null=True)),
                ('people_hosted', models.IntegerField(blank=True, default=0, null=True)),
                ('items_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('clean_transaction', models.IntegerField(blank=True, default=0, null=True)),
                ('nickname', models.CharField(blank=True, max_length=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.TextField(blank=True, null=True)),
                ('communities', models.ManyToManyField(to='base.community')),
            ],
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.userprofile'),
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('fa_icon', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(to='base.userprofile')),
            ],
        ),
    ]
