# Generated by Django 4.0.5 on 2022-07-02 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='fa_icon',
        ),
        migrations.AddField(
            model_name='community',
            name='thumbnail_image',
            field=models.ImageField(default='default.jpg', upload_to='community'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='default.jpg', upload_to='profile'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(blank=True, to='base.userprofile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='communities',
            field=models.ManyToManyField(blank=True, to='base.community'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='communities',
            field=models.ManyToManyField(blank=True, to='base.community'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item')),
                ('thumbnail', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
    ]
