# Generated by Django 4.0.5 on 2022-07-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_community_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ItemImage',
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='heading',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='sub_heading',
            field=models.CharField(max_length=50),
        ),
    ]
