# Generated by Django 4.0.5 on 2022-07-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_image_itemimage_alter_badge_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='reason',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
