# Generated by Django 4.0.5 on 2022-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_item_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='communities',
            field=models.ManyToManyField(to='base.community'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
