# Generated by Django 4.0.5 on 2022-07-03 12:43
import datetime
from django.db import migrations

def create_through_relationships(apps, schema_editor):
    UserProfile = apps.get_model('base','UserProfile')
    Membership = apps.get_model('base', 'Membership')
    for user in UserProfile.objects.all():
        for community in user.communities.all():
            Membership(
                user=user,
                community=community,
                date_joined=datetime.date.today(),
                introduction='',
            ).save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_membership'),
    ]

    operations = [
        migrations.RunPython(create_through_relationships, reverse_code=migrations.RunPython.noop),
    ]
