# Generated by Django 4.0.5 on 2022-07-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220703_1643'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='communities',
        ),
    ]
