# Generated by Django 4.0.5 on 2022-07-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_userprofile_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='communities',
            field=models.ManyToManyField(blank=True, through='base.Membership', to='base.community'),
        ),
    ]
