# Generated by Django 4.0.5 on 2022-07-04 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_userprofile_communities'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['createdAt']},
        ),
        migrations.AlterField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='badge_users', to='base.userprofile'),
        ),
        migrations.AlterField(
            model_name='item',
            name='communities',
            field=models.ManyToManyField(related_name='item_communities', to='base.community'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_user', to='base.userprofile'),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_detail', to='base.item'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_image', to='base.item'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_community', to='base.community'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_user', to='base.userprofile'),
        ),
    ]
