# Generated by Django 4.0.5 on 2022-07-05 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_item_options_alter_badge_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='items_bought',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='badge',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='badge_user', to='base.userprofile'),
        ),
    ]
