# Generated by Django 4.0.5 on 2022-07-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_userprofile_items_bought_alter_badge_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='live',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='communities',
            field=models.ManyToManyField(blank=True, related_name='user_communities', through='base.Membership', to='base.community'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile_placeholder.png', upload_to='profile'),
        ),
    ]
