# Generated by Django 4.0.5 on 2022-07-27 06:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_item_live_alter_userprofile_communities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventGuest',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('details', models.JSONField()),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_guest', to='base.item')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_guest', to='base.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='EventForm',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='event')),
                ('inputs', models.JSONField()),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.item')),
            ],
        ),
    ]
