# Generated by Django 4.1 on 2022-08-26 12:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_eventguest_eventform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_item', to='base.item')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_profile', to='base.userprofile')),
            ],
        ),
    ]
