# Generated by Django 4.1 on 2022-08-27 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.AddField(
            model_name='like',
            name='profile',
            field=models.ManyToManyField(related_name='like_profile', to='base.userprofile'),
        ),
    ]
