# Generated by Django 4.1 on 2022-08-28 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_remove_like_profile_like_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='profile',
        ),
        migrations.AddField(
            model_name='like',
            name='profiles',
            field=models.ManyToManyField(null=True, related_name='like_profile', to='base.userprofile'),
        ),
    ]
